algo = input('Digite algo')
print ('o tipo primitivo digitado é : ', type(algo))
print ('so tem espaços ?', algo.isspace())
print ('foi um numero digitado ? ', algo.isnumeric())
print ('È alfabetico ? ', algo.isalpha())
print ('È alfa numerico ? ', algo.isalnum() )
print ('esta em maiusculas ?', algo.isupper())
print ('esta em minuscula ?', algo.islower())
print ('esta capitalizada :' , algo.istitle())